// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice =
  | LanguagePickerSlice
  | FooterLinksSlice
  | SocialsSlice;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Logo Link field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_link: prismic.LinkField;

  /**
   * Slice Zone field in *footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Cookies Label field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cookies_label
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  cookies_label: prismic.RichTextField;

  /**
   * Cookies Link field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cookies_link
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cookies_link: prismic.LinkField;

  /**
   * Legal Documents Label field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_documents_label
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  legal_documents_label: prismic.RichTextField;

  /**
   * Legal Documents Link field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_documents_link
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  legal_documents_link: prismic.LinkField;

  /**
   * Privacy Policy Label field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.privacy_policy_label
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  privacy_policy_label: prismic.RichTextField;

  /**
   * Privacy Policy Link field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.privacy_policy_link
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_policy_link: prismic.LinkField;

  /**
   * Security Label field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.security_label
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  security_label: prismic.RichTextField;

  /**
   * Security Link field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.security_link
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  security_link: prismic.LinkField;

  /**
   * Copyright Label field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright_label
   * - **Tab**: Legal
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright_label: prismic.RichTextField;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | PerkColumnsSlice
  | SliderBrandsSlice
  | ExampleSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  meta_title: prismic.RichTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meta_description: prismic.RichTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type NavDocumentDataSlicesSlice =
  | LanguagePickerSlice
  | BannerSlice
  | NavItemSlice;

/**
 * Content for nav documents
 */
interface NavDocumentData {
  /**
   * Logo field in *nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Login Cta Label field in *nav*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.login_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  login_cta_label: prismic.RichTextField;

  /**
   * Login Cta Link field in *nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.login_cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  login_cta_link: prismic.LinkField;

  /**
   * Contact Us Cta Label field in *nav*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.contact_us_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_us_cta_label: prismic.RichTextField;

  /**
   * Contact Us Link  field in *nav*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.contact_us_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_us_link: prismic.LinkField;

  /**
   * Slice Zone field in *nav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavDocumentDataSlicesSlice>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

/**
 * Content for social documents
 */
interface SocialDocumentData {
  /**
   * Link field in *social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Type field in *social*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: twitter
   * - **API ID Path**: social.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    "twitter" | "linkedin" | "facebook" | "instagram",
    "filled"
  >;

  /**
   * Image field in *social*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * social document from Prismic
 *
 * - **API ID**: `social`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SocialDocumentData>, "social", Lang>;

type SubnavDocumentDataSlicesSlice = SubNavItemSlice;

type SubnavDocumentDataSlices1Slice = SubNavItemSlice;

/**
 * Content for subnav documents
 */
interface SubnavDocumentData {
  /**
   * Title field in *subnav*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: subnav.title_column_1
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_column_1: prismic.TitleField;

  /**
   * Slice Zone field in *subnav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: subnav.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubnavDocumentDataSlicesSlice> /**
   * Title field in *subnav*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: subnav.title_column_2
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  title_column_2: prismic.TitleField;

  /**
   * Slice Zone field in *subnav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: subnav.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<SubnavDocumentDataSlices1Slice>;
}

/**
 * subnav document from Prismic
 *
 * - **API ID**: `subnav`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubnavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SubnavDocumentData>, "subnav", Lang>;

export type AllDocumentTypes =
  | FooterDocument
  | HomeDocument
  | NavDocument
  | SocialDocument
  | SubnavDocument;

/**
 * Primary content in *Example → Default → Primary*
 */
export interface ExampleSliceDefaultPrimary {
  /**
   * Title field in *Example → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Example → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: example.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Example Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExampleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExampleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Example*
 */
type ExampleSliceVariation = ExampleSliceDefault;

/**
 * Example Shared Slice
 *
 * - **API ID**: `example`
 * - **Description**: Example
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExampleSlice = prismic.SharedSlice<
  "example",
  ExampleSliceVariation
>;

/**
 * Primary content in *FooterLinks → Default → Primary*
 */
export interface FooterLinksSliceDefaultPrimary {
  /**
   * Title field in *FooterLinks → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *FooterLinks → Items*
 */
export interface FooterLinksSliceDefaultItem {
  /**
   * Link Name field in *FooterLinks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].link_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link_name: prismic.RichTextField;

  /**
   * Link Value field in *FooterLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].link_value
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_value: prismic.LinkField;
}

/**
 * Default variation for FooterLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: FooterLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterLinksSliceDefaultPrimary>,
  Simplify<FooterLinksSliceDefaultItem>
>;

/**
 * Slice variation for *FooterLinks*
 */
type FooterLinksSliceVariation = FooterLinksSliceDefault;

/**
 * FooterLinks Shared Slice
 *
 * - **API ID**: `footer_links`
 * - **Description**: FooterLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSlice = prismic.SharedSlice<
  "footer_links",
  FooterLinksSliceVariation
>;

/**
 * Primary content in *NavItem → Default → Primary*
 */
export interface NavItemSliceDefaultPrimary {
  /**
   * Name field in *NavItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Link field in *NavItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Sub Nav Item field in *NavItem → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.default.primary.sub_nav_item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_nav_item: prismic.ContentRelationshipField<"subnav">;
}

/**
 * Primary content in *NavItem → Items*
 */
export interface NavItemSliceDefaultItem {
  /**
   * Child Name field in *NavItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].child_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  child_name: prismic.RichTextField;

  /**
   * Child Link field in *NavItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].child_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  child_link: prismic.LinkField;
}

/**
 * Default variation for NavItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: NavItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavItemSliceDefaultPrimary>,
  Simplify<NavItemSliceDefaultItem>
>;

/**
 * Slice variation for *NavItem*
 */
type NavItemSliceVariation = NavItemSliceDefault;

/**
 * NavItem Shared Slice
 *
 * - **API ID**: `nav_item`
 * - **Description**: NavItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavItemSlice = prismic.SharedSlice<
  "nav_item",
  NavItemSliceVariation
>;

/**
 * Primary content in *PerkColumns → Default → Primary*
 */
export interface PerkColumnsSliceDefaultPrimary {
  /**
   * Title field in *PerkColumns → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *PerkColumns → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *PerkColumns → Items*
 */
export interface PerkColumnsSliceDefaultItem {
  /**
   * Title field in *PerkColumns → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *PerkColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *PerkColumns → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Perk One field in *PerkColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.items[].perk_one
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  perk_one: prismic.RichTextField;

  /**
   * Perk Two field in *PerkColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.items[].perk_two
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  perk_two: prismic.RichTextField;

  /**
   * Perk Three field in *PerkColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perk_columns.items[].perk_three
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  perk_three: prismic.RichTextField;
}

/**
 * Default variation for PerkColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerkColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PerkColumnsSliceDefaultPrimary>,
  Simplify<PerkColumnsSliceDefaultItem>
>;

/**
 * Slice variation for *PerkColumns*
 */
type PerkColumnsSliceVariation = PerkColumnsSliceDefault;

/**
 * PerkColumns Shared Slice
 *
 * - **API ID**: `perk_columns`
 * - **Description**: PerkColumns
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerkColumnsSlice = prismic.SharedSlice<
  "perk_columns",
  PerkColumnsSliceVariation
>;

/**
 * Primary content in *SliderBrands → Default → Primary*
 */
export interface SliderBrandsSliceDefaultPrimary {
  /**
   * TItle field in *SliderBrands → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_brands.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *SliderBrands → Items*
 */
export interface SliderBrandsSliceDefaultItem {
  /**
   * Image field in *SliderBrands → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_brands.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SliderBrands Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderBrandsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderBrandsSliceDefaultPrimary>,
  Simplify<SliderBrandsSliceDefaultItem>
>;

/**
 * Primary content in *SliderBrands → Dark → Primary*
 */
export interface SliderBrandsSliceDarkPrimary {
  /**
   * TItle field in *SliderBrands → Dark → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_brands.dark.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *SliderBrands → Items*
 */
export interface SliderBrandsSliceDarkItem {
  /**
   * Image field in *SliderBrands → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_brands.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Dark variation for SliderBrands Slice
 *
 * - **API ID**: `dark`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderBrandsSliceDark = prismic.SharedSliceVariation<
  "dark",
  Simplify<SliderBrandsSliceDarkPrimary>,
  Simplify<SliderBrandsSliceDarkItem>
>;

/**
 * Slice variation for *SliderBrands*
 */
type SliderBrandsSliceVariation =
  | SliderBrandsSliceDefault
  | SliderBrandsSliceDark;

/**
 * SliderBrands Shared Slice
 *
 * - **API ID**: `slider_brands`
 * - **Description**: SliderBrands
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderBrandsSlice = prismic.SharedSlice<
  "slider_brands",
  SliderBrandsSliceVariation
>;

/**
 * Primary content in *Socials → Items*
 */
export interface SocialsSliceDefaultItem {
  /**
   * Social field in *Socials → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: socials.items[].social
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social: prismic.ContentRelationshipField<"social">;
}

/**
 * Default variation for Socials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Socials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialsSliceDefaultItem>
>;

/**
 * Slice variation for *Socials*
 */
type SocialsSliceVariation = SocialsSliceDefault;

/**
 * Socials Shared Slice
 *
 * - **API ID**: `socials`
 * - **Description**: Socials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialsSlice = prismic.SharedSlice<
  "socials",
  SocialsSliceVariation
>;

/**
 * Primary content in *SubNavItem → Default → Primary*
 */
export interface SubNavItemSliceDefaultPrimary {
  /**
   * Label field in *SubNavItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *SubNavItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for SubNavItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubNavItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubNavItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SubNavItem → withIcon → Primary*
 */
export interface SubNavItemSliceWithIconPrimary {
  /**
   * Label field in *SubNavItem → withIcon → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.withIcon.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *SubNavItem → withIcon → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.withIcon.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Icon field in *SubNavItem → withIcon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.withIcon.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * withIcon variation for SubNavItem Slice
 *
 * - **API ID**: `withIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubNavItemSliceWithIcon = prismic.SharedSliceVariation<
  "withIcon",
  Simplify<SubNavItemSliceWithIconPrimary>,
  never
>;

/**
 * Primary content in *SubNavItem → Card → Primary*
 */
export interface SubNavItemSliceCardPrimary {
  /**
   * Label field in *SubNavItem → Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.card.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Description field in *SubNavItem → Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.card.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *SubNavItem → Card → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.card.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *SubNavItem → Card → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_nav_item.card.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Card variation for SubNavItem Slice
 *
 * - **API ID**: `card`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubNavItemSliceCard = prismic.SharedSliceVariation<
  "card",
  Simplify<SubNavItemSliceCardPrimary>,
  never
>;

/**
 * Slice variation for *SubNavItem*
 */
type SubNavItemSliceVariation =
  | SubNavItemSliceDefault
  | SubNavItemSliceWithIcon
  | SubNavItemSliceCard;

/**
 * SubNavItem Shared Slice
 *
 * - **API ID**: `sub_nav_item`
 * - **Description**: SubNavItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubNavItemSlice = prismic.SharedSlice<
  "sub_nav_item",
  SubNavItemSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      NavDocumentDataSlicesSlice,
      SocialDocument,
      SocialDocumentData,
      SubnavDocument,
      SubnavDocumentData,
      SubnavDocumentDataSlicesSlice,
      SubnavDocumentDataSlices1Slice,
      AllDocumentTypes,
      ExampleSlice,
      ExampleSliceDefaultPrimary,
      ExampleSliceVariation,
      ExampleSliceDefault,
      FooterLinksSlice,
      FooterLinksSliceDefaultPrimary,
      FooterLinksSliceDefaultItem,
      FooterLinksSliceVariation,
      FooterLinksSliceDefault,
      NavItemSlice,
      NavItemSliceDefaultPrimary,
      NavItemSliceDefaultItem,
      NavItemSliceVariation,
      NavItemSliceDefault,
      PerkColumnsSlice,
      PerkColumnsSliceDefaultPrimary,
      PerkColumnsSliceDefaultItem,
      PerkColumnsSliceVariation,
      PerkColumnsSliceDefault,
      SliderBrandsSlice,
      SliderBrandsSliceDefaultPrimary,
      SliderBrandsSliceDefaultItem,
      SliderBrandsSliceDarkPrimary,
      SliderBrandsSliceDarkItem,
      SliderBrandsSliceVariation,
      SliderBrandsSliceDefault,
      SliderBrandsSliceDark,
      SocialsSlice,
      SocialsSliceDefaultItem,
      SocialsSliceVariation,
      SocialsSliceDefault,
      SubNavItemSlice,
      SubNavItemSliceDefaultPrimary,
      SubNavItemSliceWithIconPrimary,
      SubNavItemSliceCardPrimary,
      SubNavItemSliceVariation,
      SubNavItemSliceDefault,
      SubNavItemSliceWithIcon,
      SubNavItemSliceCard,
    };
  }
}
