// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer_links: dynamic(() => import("./FooterLinks")),
  nav_item: dynamic(() => import("./NavItem")),
  perk_columns: dynamic(() => import("./PerkColumns")),
  slider_brands: dynamic(() => import("./SliderBrands")),
  socials: dynamic(() => import("./Socials")),
  sub_nav_item: dynamic(() => import("./SubNavItem")),
};
