// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  example: dynamic(() => import("./Example")),
  footer_links: dynamic(() => import("./FooterLinks")),
  nav_item: dynamic(() => import("./NavItem")),
  socials: dynamic(() => import("./Socials")),
  sub_nav_item: dynamic(() => import("./SubNavItem")),
};
